### ISSUE TITLE
There are some mistakes. Who can help me

### ISSUE THREAD

**Issue by luoyexuge** [jpmml/jpmml-lightgbm#14]
lightgbm shuubiasahi$ java -jar target/converter-executable-1.2-SNAPSHOT.jar  --lgbm-input /Users/shuubiasahi/Documents/python/credit-tfgan/xml/lightgbm.txt --pmml-output /Users/shuubiasahi/Documents/python/credit-tfgan/xml/lightgbm.pmml
Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.jpmml.lightgbm.Section.getInt(Section.java:46)
	at org.jpmml.lightgbm.Tree.load(Tree.java:76)
	at org.jpmml.lightgbm.GBDT.load(GBDT.java:108)
	at org.jpmml.lightgbm.LightGBMUtil.loadGBDT(LightGBMUtil.java:61)
	at org.jpmml.lightgbm.LightGBMUtil.loadGBDT(LightGBMUtil.java:53)
	at org.jpmml.lightgbm.Main.run(Main.java:122)
	at org.jpmml.lightgbm.Main.main(Main.java:115)

**Comment by azaaza0319** [comment]
Hi I have the same issue here. Could someone reopen the issue and help?
Attached is my model file. Is it due to the model does not have "num_cat"?
[lightgbm.txt](https://github.com/jpmml/jpmml-lightgbm/files/2907875/lightgbm.txt)

FYI lightgbm version is 2.0.2
